eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_SERVER:http://localhost:9411/api/v2/spans}
  tracing:
    sampling:
      probability: 1.0
# spring:
#   rabbitmq:
#     host: localhost
#     port: 5672
#     username: guest
#     username: guest


# okta:
#   oauth2:
#     issuer: https://dev-24048772.okta.com/oauth2/default
#     audience: api://default
# spring:
#   zipkin:
#     baseUrl: http://zipkin-svc:9411
